#ifndef PROJECTM_PLAYLIST_EXPORT_H
#define PROJECTM_PLAYLIST_EXPORT_H

#define PROJECTM_PLAYLIST_EXPORT
#define PROJECTM_PLAYLIST_NO_EXPORT
#define PROJECTM_PLAYLIST_DEPRECATED
#define PROJECTM_PLAYLIST_DEPRECATED_EXPORT
#define PROJECTM_PLAYLIST_DEPRECATED_NO_EXPORT

#endif /* PROJECTM_PLAYLIST_EXPORT_H */
