#ifndef PROJECTM_EXPORT_H
#define PROJECTM_EXPORT_H

#define PROJECTM_EXPORT
#define PROJECTM_NO_EXPORT
#define PROJECTM_DEPRECATED
#define PROJECTM_DEPRECATED_EXPORT
#define PROJECTM_DEPRECATED_NO_EXPORT

#endif /* PROJECTM_EXPORT_H */
